config_name: base_modl,k=10
description: "base config, k=10. Restore weights from <base_modl,k=1>"

n_layers: 5
k_iters: 10
epochs: 50

dataset_name: modl_dataset
dataset_params:
  dataroot_in: './data/single/TrainingSet/FullSample/lax'
  dataroot_in_test: './data/single/TestSet_60/FullSample/lax'
  dataroot_mask: './data/mask'
  sigma: 0.01
val_data: False
batch_size: 4

model_name: base_modl

restore_weights: final #False, best, inter, final
restore_path: './workspace/base_modl,k=1/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True