config_name: base_modl,k=1
description: "base config, k=1"

n_layers: 5
k_iters: 1
epochs: 50

dataset_name: modl_dataset
dataset_params:
  dataroot_in: '/home3/HWGroup/wangcy/JunLyu/wgm/singlec/Newsingle/lax_single_channel/data/single/TrainingSet/FullSample/sax'
  dataroot_in_test: '/home3/HWGroup/wangcy/JunLyu/wgm/singlec/Newsingle/lax_single_channel/data/single/TestSet_60/FullSample/sax'
  dataroot_in_csm: '/home3/HWGroup/wangcy/JunLyu/wgm/singlec/Newsingle/lax_single_channel/data/mul/TrainingSet/sax_csm'
  dataroot_in_csm_test: '/home3/HWGroup/wangcy/JunLyu/wgm/singlec/Newsingle/lax_single_channel/data/mul/TestSet_60/sax_csm'
  dataroot_mask: '/home3/HWGroup/wangcy/JunLyu/wgm/singlec/Newsingle/lax_single_channel/data/mask'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_modl

restore_weights: False #False, best, inter, final
restore_path: 

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True